### ISSUE TITLE
Build is failing

### ISSUE THREAD

**Issue by J-Ziegler** [J-Ziegler/3601-S16-lab5_json-data-processing#13]
Need to fix at some point.

**Comment by dragoteon** [comment]
The build is failing because it is not recognizing "should" in the code.

example.

it('should respond with the newly created student', function() {
      newStudent.name.**should**.equal('New Student');
      newStudent.info.**should**.equal('This is the brand new student!!!');
    });


locations 

1) Student API: POST /api/students should respond with the newly created student:

     TypeError: Cannot read property 'should' of undefined
      at Context.<anonymous> (server/api/student/student.integration.js:53:22)
      at Test.<anonymous> (server/api/student/student.integration.js:48:11)
      at Test.assert (node_modules/supertest/lib/test.js:156:6)
      at Server.assert (node_modules/supertest/lib/test.js:127:12)
      at emitCloseNT (net.js:1521:8)

  2) Student API: GET /api/students/:id should respond with the requested student:

     TypeError: Cannot read property 'should' of undefined
      at Context.<anonymous> (server/api/student/student.integration.js:81:19)
      at Test.<anonymous> (server/api/student/student.integration.js:72:11)
      at Test.assert (node_modules/supertest/lib/test.js:156:6)
      at Server.assert (node_modules/supertest/lib/test.js:127:12)
      at emitCloseNT (net.js:1521:8)

  3) Student API: PUT /api/students/:id should respond with the updated student:

     TypeError: Cannot read property 'should' of undefined
      at Context.<anonymous> (server/api/student/student.integration.js:113:26)
      at Test.<anonymous> (server/api/student/student.integration.js:104:11)
      at Test.assert (node_modules/supertest/lib/test.js:156:6)
      at Server.assert (node_modules/supertest/lib/test.js:127:12)
      at emitCloseNT (net.js:1521:8)

**Comment by J-Ziegler** [comment]
Probably better.
